apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.redis.app }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack
    app: {{ .Values.redis.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.redis.app }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: {{ .Values.redis.leader.container.ports.podSource }}
      targetPort: {{ .Values.prometheusPort }}
      path: /metrics
      interval: 30s
