{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.test }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack   # must match Prometheus release name
spec:
  selector:
    matchLabels:
      app: {{ .Values.test }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: 30s
{{- end }}