{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-metrics
  labels:
    app: {{ include "myapp.name" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.metrics.port }}
      targetPort: http
  selector:
    app: {{ include "myapp.name" . }}
{{- end }}